spring.application.name=tasktrack-api
spring.mongodb.uri=mongodb+srv://arroiseeu_db_user:9dAlKPmlpCmINhbj@cluster0.kqc3cqz.mongodb.net/tasktrack_db?retryWrites=true&w=majority
server.servlet.context-path=/api
